version: 0.2
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket politeness-api --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputSamTemplate.yaml
