AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  politenessapi:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handlePoliteness.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Description: ''
      MemorySize: 128
      Timeout: 3
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /politeness-api
            Method: POST
      Environment:
        Variables:
          CLIENT_ID: '461546631287.460699053317'
  politenessoauth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handleOauth.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::761270497423:role/service-role/myFirstLambdaServiceRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /politeness-oauth
            Method: GET

